import { NoticeAnalysis } from "../types/analysis";

const ANALYSIS_API_BASE_URL = "http://127.0.0.1:8787";

export async function loadNoticeAnalysis(bidNo: string, bidOrd: string): Promise<NoticeAnalysis> {
  try {
    const response = await fetch(`${ANALYSIS_API_BASE_URL}/api/notices/${bidNo}/${bidOrd}/analysis`);
    const payload = await response.json();
    if (response.ok) {
      return payload as NoticeAnalysis;
    }
  } catch {
    // Fall back to the static artifact generated by GitHub Actions.
  }

  const staticResponse = await fetch(`data/analyses/${bidNo}-${bidOrd}.json`, { cache: "no-store" });
  if (!staticResponse.ok) {
    throw new Error("분석 API 호출에 실패했고 사전 분석 JSON도 찾지 못했습니다.");
  }
  return (await staticResponse.json()) as NoticeAnalysis;
}
