import { NoticeAnalysis } from "../types/analysis";

const ANALYSIS_API_BASE_URL = import.meta.env.VITE_ANALYSIS_API_BASE_URL ?? "";

export async function loadNoticeDocuments(bidNo: string, bidOrd: string): Promise<NoticeAnalysis> {
  const response = await fetch(`${ANALYSIS_API_BASE_URL}/api/notices/${bidNo}/${bidOrd}/documents`, {
    cache: "no-store",
  });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }
  return (await response.json()) as NoticeAnalysis;
}

export async function loadNoticeAnalysis(bidNo: string, bidOrd: string): Promise<NoticeAnalysis> {
  try {
    const response = await fetch(`${ANALYSIS_API_BASE_URL}/api/notices/${bidNo}/${bidOrd}/analysis`, {
      cache: "no-store",
    });
    const payload = await response.json();
    if (response.ok) {
      return payload as NoticeAnalysis;
    }
  } catch {
    // Fall back to the static artifact generated by GitHub Actions.
  }

  const staticResponse = await fetch(`data/analyses/${bidNo}-${bidOrd}.json`, { cache: "no-store" });
  if (!staticResponse.ok) {
    throw new Error("분석 API 호출에 실패했고 사전 분석 JSON도 찾지 못했습니다.");
  }
  return (await staticResponse.json()) as NoticeAnalysis;
}
