import { NoticeAnalysis } from "../types/analysis";
import { apiUrl, assetUrl, fetchJson } from "./baseUrl";

export async function loadNoticeDocuments(bidNo: string, bidOrd: string): Promise<NoticeAnalysis> {
  const payload = await fetchJson<NoticeAnalysis>(apiUrl(`/api/notices/${bidNo}/${bidOrd}/documents`), {
    cache: "no-store",
  });
  return normalizeDocumentUrls(payload);
}

export async function loadNoticeAnalysis(bidNo: string, bidOrd: string): Promise<NoticeAnalysis> {
  try {
    const payload = await fetchJson<NoticeAnalysis>(apiUrl(`/api/notices/${bidNo}/${bidOrd}/analysis`), {
      cache: "no-store",
    });
    return normalizeDocumentUrls(payload);
  } catch {
    // Fall back to the static artifact generated by GitHub Actions.
  }

  const payload = await fetchJson<NoticeAnalysis>(`data/analyses/${bidNo}-${bidOrd}.json`, { cache: "no-store" });
  return normalizeDocumentUrls(payload);
}

function normalizeDocumentUrls(payload: NoticeAnalysis): NoticeAnalysis {
  return {
    ...payload,
    documents: (payload.documents ?? []).map((document) => ({
      ...document,
      fileUrl: assetUrl(document.fileUrl),
      originalFileUrl: assetUrl(document.originalFileUrl),
      pdfUrl: assetUrl(document.pdfUrl),
    })),
  };
}
